version: "3.2"

services:
  jupyter:
    build: ./main_root
    container_name: jupyter
    stdin_open: true
    restart: always
    ports:
      - 8899:8888
    volumes:
      - ./main_root:/usr/src/app
    working_dir: /usr/src/app
